// src/features/machinesSlice.js
import { createSlice } from '@reduxjs/toolkit';

const machinesSlice = createSlice({
  name: 'machines',
  initialState: [
    { id: 1, name: 'Machine A', status: 'Active' },
    { id: 2, name: 'Machine B', status: 'Inactive' },
  ],
  reducers: {
    toggleStatus: (state, action) => {
      const machine = state.find(machine => machine.id === action.payload);
      if (machine) {
        machine.status = machine.status === 'Active' ? 'Inactive' : 'Active';
      }
    },
    addMachine: (state, action) => {
      state.push(action.payload);
    },
  },
});

export const { toggleStatus, addMachine } = machinesSlice.actions;
export default machinesSlice.reducer;


/*


createSlice: This function simplifies creating a slice of the
 Redux store by combining actions and reducers.

name: This is a unique identifier for the slice.

initialState: This defines the initial state of the machines, with two example machines.
reducers:

toggleStatus: This function takes the machine ID as an
 action payload and toggles its status between "Active"
  and "Inactive".


addMachine: This function allows adding a new machine 
to the state.

Exported Actions: The actions generated by createSlice are 
exported for use in components.


*/